---
Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: eu-central-1a
            ImageId: ami-00a205cb8e06c3c4e
            InstanceType: t2.micro
